### ISSUE TITLE
Query question

### ISSUE THREAD

**Issue by ewindso** [MichaelSolati/geofirestore#11]
Would it be possible / efficient to query based on the rectangular area of 2 geo points, instead of one and a radius?  Thanks!

**Comment by MichaelSolati** [comment]
Possibly, but it'll be a pain. Drawing a bounding box of geohash points is likely doable, but will require much more validation as the data is returned to the client to ensure it exists in the appropriate area (and is not something I'm looking at implementing). Genuinely the purpose of this package is to find locations near a point, and the method used does just that.

However if you're interested in doing this for yourself, by all means fork it, or look into geohashing as the means of doing this.

**Comment by MvRemmerden** [comment]
That would be amazing! One use case that I have seen very often is to show a Google Map, get the rectangular area and then query for all places inside that area. With a circular radius, you will always show results that fall out of the map.

**Comment by MichaelSolati** [comment]
Unfortunately that would add an additional layer of complexity where I wanted to build this similar to how the regular geofire library works (as well as other DB do geoqueries based on radius). What I would advise is to grab the two coordinates (the NE and SW points) and find the delta between the latitude and longitude of those two points. For whichever one is longer, multiply that by 0.7, and use it as the radius of your query. When the point come in you can do a quick check to see if it fits inside of your bounding box.

To be honest, because of how geofirestore makes it's queries, if I was to implement that I would be doing something like that anyway so I stand by it being a solution.

**Comment by MvRemmerden** [comment]
Interesting, that's what I had thought about as well, but Frank van Puffelen (@puf) recommended against it: https://twitter.com/puf/status/1023956665844948993

**Comment by puf** [comment]
GeoFire queries geohash ranges, which are (roughly) rectangular. It then culls the items that are not in range, to turn it into the requested circle ([code](https://github.com/MichaelSolati/geofirestore/blob/dev/src/query.ts#L194-L201)). If you want a rectangular result, it's much more efficient to simply skip that culling than to do another culling from a circle back to a rectagle.

**Comment by MichaelSolati** [comment]
@puf is absolutely right, but that will likely require a fork and change to this project (and I'm a bit too lazy to do that ATM), this may be something to look into at a later point. I just wouldn't have the time to do it now (I AM OPEN TO PRs/DISCUSSIONS)

**Comment by MvRemmerden** [comment]
Great, will use the less performant technique for the prototype and start a PR when I'm going into production mode! 😃

**Comment by bgmort** [comment]
Did anybody ever start the work on this? I haven't dug into the code base to see how hard it would be, but if nobody has attempted it, I will take a stab at it.  I want rectangular queries for the same reason @MvRemmerden stated, and I'm sure many others would like to use it that way.
