### ISSUE TITLE
using set deletes my existing document

### ISSUE THREAD

**Issue by R-D-P** [MichaelSolati/geofirestore#40]
Hello , 
Thanks for the time you've put into this.
Before writing this I searched a lot on SO but couldn't find anything.
I may be doing something wrong but when I use geofirestore.set, it deletes the existing fields of the document and updates them with the geohas and coordinates.
My code for updation is as follows:
//uid is the userid of the user profile
geoFirestore.set(uid, { coordinates: location}).then(() => {
  console.log('Provided key has been added to GeoFirestore');
}, (error) => {
  console.log('Error: ' + error);
})

**Comment by MichaelSolati** [comment]
The docs refer to this behavior, so while it may not be ideal, it is by design. [You can see that in the second paragraph of the set docs](https://github.com/MichaelSolati/geofirestore/blob/master/README.md#geofirestoresetkeyordocuments-document-customkey).

However in version 3.0.0 the set and update will align with how the Firestore SDK works, where you can send options for merging and what not.
