### ISSUE TITLE
orderBy inside inner query doesn't work

### ISSUE THREAD

**Issue by iamswain25** [MichaelSolati/geofirestore#41]
this one works
`const query = ref => ref.limit(4)`
`const geoQuery = geofirestore.query({ center, radius, query })`

this one doesn't
`const query = ref => ref.orderBy('d.createdAt', 'desc')`
`const geoQuery = geofirestore.query({ center, radius, query })`

nothing comes through key_entered event listener
I set the indexing on firestore as it advises me to: `d.createdAt DESC g ASC`

**Comment by MichaelSolati** [comment]
So `ref.limit` will not really work all the time... It's a side effect of how the service works, you can see an [explanation here](https://github.com/MichaelSolati/geofirestore/issues/26#issuecomment-411519510).

Anyway, I did some digging and testing, and here are a few issues regarding Firestore queries and GeoFirestore (and the docs should and will be updated to reflect this).

1. You can not use `startAt` or similar modifiers (`startAfter`, `endBefore`, `endAt`) with GeoFirestore since we append the geo based modifiers to the end of a query and you cannot specify an `orderBy()` constraint after calling `startAt()`, `startAfter()`, `endBefore()` or `endAt()`.
2. It looks like while Firestore could support two `orderBy`s, it can not support two `orderBy`s AND two of the previously mentioned modifiers (`startAt`, `startAfter`, `endBefore`, `endAt`). It seems as if it has been somewhat documented as an [issue here](https://stackoverflow.com/a/47541800) by a member of the Firebase team.

I'll be updating the docs to reflect this.
